/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FixHub API
 * FixHub backend API docs
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';

export type GetParams = {
  /**
   * @minLength 1
   */
  input?: string;
};

export type Get200 = {
  message: string;
  success: boolean;
  /** @nullable */
  echo: string | null;
  db: boolean;
};

export const getFixHubAPI = (axiosInstance: AxiosInstance = axios.default) => {
  /**
   * Health check API
   */
  const get = (
    params?: GetParams,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<Get200>> => {
    return axiosInstance.get(`/`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };

  return { get };
};
export type GetResult = AxiosResponse<Get200>;
