/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FixHub API
 * FixHub backend API docs
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customInstance } from './mutator';
import type { ErrorType, BodyType } from './mutator';
export type GetPublicIssuesResponseMeta = {
  totalItemCount: number;
  currentItemCount: number;
  itemsPerPage: number;
  currentPage: number;
  totalPages: number;
};

export interface PublicIssueItem {
  id: string;
  title: string;
  teamName: string;
  author: string;
  tags: string[];
  summary: string;
  commentCount: number;
  createdAt: string;
}

export interface GetPublicIssuesResponse {
  meta: GetPublicIssuesResponseMeta;
  data: PublicIssueItem[];
}

export type PublicBadRequestError = {
  code: string;
  message: string;
};

export interface PublicBadRequest {
  error: PublicBadRequestError;
}

export type DetailBadRequestError = {
  code: string;
  message: string;
};

export interface DetailBadRequest {
  error: DetailBadRequestError;
}

export type NotFoundError = {
  code: string;
  message: string;
};

export interface NotFound {
  error: NotFoundError;
}

export type CreateBadRequestError = {
  code: string;
  message: string;
};

export interface CreateBadRequest {
  error: CreateBadRequestError;
}

export type UnauthorizedError = {
  code: string;
  message: string;
};

export interface Unauthorized {
  error: UnauthorizedError;
}

export type ForbiddenError = {
  code: string;
  message: string;
};

export interface Forbidden {
  error: ForbiddenError;
}

export type GetComments200DataItemRepliesItemRepliesItem = {
  [key: string]: unknown;
};

export type GetComments200DataItemRepliesItem = {
  id: string;
  content: string;
  author: string;
  /** @nullable */
  parentId: string | null;
  isAdopted: boolean;
  createdAt: string;
  replies: GetComments200DataItemRepliesItemRepliesItem[];
};

export type GetComments200DataItem = {
  id: string;
  content: string;
  author: string;
  /** @nullable */
  parentId: string | null;
  isAdopted: boolean;
  createdAt: string;
  replies: GetComments200DataItemRepliesItem[];
};

export type GetComments200 = {
  data: GetComments200DataItem[];
};

export type GetComments404Error = {
  code: string;
  message: string;
};

export type GetComments404 = {
  error: GetComments404Error;
};

export type PostIssuesIdCommentsBody = {
  /**
   * @minLength 1
   * @maxLength 1000
   */
  content: string;
  /**
   * @minLength 1
   * @nullable
   */
  parentId: string | null;
};

export type PostIssuesIdComments201 = {
  id: string;
  author: string;
  /** @pattern ^\d{4}-\d{2}-\d{2}\([일월화수목금토]\)$ */
  createdAt: string;
};

export type PostIssuesIdComments400Error = {
  code: string;
  message: string;
};

export type PostIssuesIdComments400 = {
  error: PostIssuesIdComments400Error;
};

export type PostIssuesIdComments401Error = {
  code: string;
  message: string;
};

export type PostIssuesIdComments401 = {
  error: PostIssuesIdComments401Error;
};

export type PostIssuesIdComments404Error = {
  code: string;
  message: string;
};

export type PostIssuesIdComments404 = {
  error: PostIssuesIdComments404Error;
};

export type AdoptComment200Status =
  (typeof AdoptComment200Status)[keyof typeof AdoptComment200Status];

export const AdoptComment200Status = {
  SOLVED: 'SOLVED',
} as const;

export type AdoptComment200 = {
  issueId: string;
  commentId: string;
  rewardedScore: number;
  reason: string;
  status: AdoptComment200Status;
};

export type AdoptComment401Error = {
  code: string;
  message: string;
};

export type AdoptComment401 = {
  error: AdoptComment401Error;
};

export type AdoptComment403Error = {
  code: string;
  message: string;
};

export type AdoptComment403 = {
  error: AdoptComment403Error;
};

export type AdoptComment404Error = {
  code: string;
  message: string;
};

export type AdoptComment404 = {
  error: AdoptComment404Error;
};

export type AdoptComment409Error = {
  code: string;
  message: string;
};

export type AdoptComment409 = {
  error: AdoptComment409Error;
};

export type UpdateCommentBody = {
  /**
   * @minLength 1
   * @maxLength 1000
   */
  content: string;
};

export type UpdateComment200 = {
  id: string;
  content: string;
  updatedAt: string;
};

export type UpdateComment400Error = {
  code: string;
  message: string;
};

export type UpdateComment400 = {
  error: UpdateComment400Error;
};

export type UpdateComment401Error = {
  code: string;
  message: string;
};

export type UpdateComment401 = {
  error: UpdateComment401Error;
};

export type UpdateComment403Error = {
  code: string;
  message: string;
};

export type UpdateComment403 = {
  error: UpdateComment403Error;
};

export type UpdateComment404Error = {
  code: string;
  message: string;
};

export type UpdateComment404 = {
  error: UpdateComment404Error;
};

export type GetParams = {
  /**
   * @minLength 1
   */
  input?: string;
};

export type Get200 = {
  message: string;
  success: boolean;
  /** @nullable */
  echo: string | null;
  db: boolean;
};

export type PostAuthSignupBody = {
  /** @minLength 2 */
  name: string;
  email: string;
  /** @minLength 8 */
  password: string;
};

export type PostAuthSignup201User = {
  id: string;
  name: string;
};

export type PostAuthSignup201 = {
  message: string;
  user: PostAuthSignup201User;
};

export type PostAuthSignup400Error = {
  /** 에러 코드 (CONFLICT, UNAUTHORIZED, BAD_REQUEST 등) */
  code: string;
  /** 에러 상세 메시지 */
  message: string;
};

export type PostAuthSignup400 = {
  error: PostAuthSignup400Error;
};

export type PostAuthSignup409Error = {
  /** 에러 코드 (CONFLICT, UNAUTHORIZED, BAD_REQUEST 등) */
  code: string;
  /** 에러 상세 메시지 */
  message: string;
};

export type PostAuthSignup409 = {
  error: PostAuthSignup409Error;
};

export type PostAuthLoginBody = {
  email: string;
  password: string;
};

export type PostAuthLogin200User = {
  id: string;
  name: string;
};

export type PostAuthLogin200 = {
  message: string;
  user: PostAuthLogin200User;
};

export type PostAuthLogin400Error = {
  /** 에러 코드 (CONFLICT, UNAUTHORIZED, BAD_REQUEST 등) */
  code: string;
  /** 에러 상세 메시지 */
  message: string;
};

export type PostAuthLogin400 = {
  error: PostAuthLogin400Error;
};

export type PostAuthLogin401Error = {
  /** 에러 코드 (CONFLICT, UNAUTHORIZED, BAD_REQUEST 등) */
  code: string;
  /** 에러 상세 메시지 */
  message: string;
};

export type PostAuthLogin401 = {
  error: PostAuthLogin401Error;
};

export type PostAuthLogout401Error = {
  /** 에러 코드 (CONFLICT, UNAUTHORIZED, BAD_REQUEST 등) */
  code: string;
  /** 에러 상세 메시지 */
  message: string;
};

export type PostAuthLogout401 = {
  error: PostAuthLogout401Error;
};

export type PostTeamsBody = {
  /**
   * @minLength 1
   * @maxLength 50
   */
  name: string;
  /** @maxLength 500 */
  description?: string;
};

export type PostTeams201 = {
  teamId: string;
  name: string;
  /** @nullable */
  description: string | null;
  inviteCode: string;
};

export type PostTeams400Error = {
  code: string;
  message: string;
};

export type PostTeams400 = {
  error: PostTeams400Error;
};

export type PostTeams401Error = {
  code: string;
  message: string;
};

export type PostTeams401 = {
  error: PostTeams401Error;
};

export type GetTeams200DataItem = {
  teamId: string;
  name: string;
  memberCount: number;
  /** @nullable */
  ownerId: string | null;
};

export type GetTeams200 = {
  data: GetTeams200DataItem[];
};

export type GetTeams401Error = {
  code: string;
  message: string;
};

export type GetTeams401 = {
  error: GetTeams401Error;
};

export type GetIssuesSearchParams = {
  /**
   * @minLength 1
   */
  search?: string;
};

export type GetIssuesSearch200Meta = {
  totalItemCount: number;
  currentItemCount: number;
  itemsPerPage: number;
  currentPage: number;
  totalPages: number;
};

export type GetIssuesSearch200DataItemStatus =
  (typeof GetIssuesSearch200DataItemStatus)[keyof typeof GetIssuesSearch200DataItemStatus];

export const GetIssuesSearch200DataItemStatus = {
  UNSOLVED: 'UNSOLVED',
  SOLVED: 'SOLVED',
} as const;

export type GetIssuesSearch200DataItem = {
  id: string;
  title: string;
  teamName: string;
  author: string;
  tag: string[];
  status: GetIssuesSearch200DataItemStatus;
  commentCount: number;
  createdAt: string;
};

export type GetIssuesSearch200 = {
  meta: GetIssuesSearch200Meta;
  data: GetIssuesSearch200DataItem[];
};

export type GetIssuesPublicParams = {
  page?: number;
  limit?: number;
};

export type GetTeamsTeamIdIssuesIssueId200Status =
  (typeof GetTeamsTeamIdIssuesIssueId200Status)[keyof typeof GetTeamsTeamIdIssuesIssueId200Status];

export const GetTeamsTeamIdIssuesIssueId200Status = {
  UNSOLVED: 'UNSOLVED',
  SOLVED: 'SOLVED',
} as const;

export type GetTeamsTeamIdIssuesIssueId200LogsItemLogType =
  (typeof GetTeamsTeamIdIssuesIssueId200LogsItemLogType)[keyof typeof GetTeamsTeamIdIssuesIssueId200LogsItemLogType];

export const GetTeamsTeamIdIssuesIssueId200LogsItemLogType = {
  SENT: 'SENT',
  RECEIVED: 'RECEIVED',
} as const;

export type GetTeamsTeamIdIssuesIssueId200LogsItem = {
  logId: string;
  logType: GetTeamsTeamIdIssuesIssueId200LogsItemLogType;
  /** @nullable */
  source: string | null;
  message: string;
};

export type GetTeamsTeamIdIssuesIssueId200 = {
  id: string;
  title: string;
  content: string;
  tag: string[];
  author: string;
  errorLog: string;
  isPublic: boolean;
  status: GetTeamsTeamIdIssuesIssueId200Status;
  logs: GetTeamsTeamIdIssuesIssueId200LogsItem[];
};

export type PostTeamsTeamIdIssuesBodyLogsItemLogType =
  (typeof PostTeamsTeamIdIssuesBodyLogsItemLogType)[keyof typeof PostTeamsTeamIdIssuesBodyLogsItemLogType];

export const PostTeamsTeamIdIssuesBodyLogsItemLogType = {
  SENT: 'SENT',
  RECEIVED: 'RECEIVED',
} as const;

export type PostTeamsTeamIdIssuesBodyLogsItem = {
  logType: PostTeamsTeamIdIssuesBodyLogsItemLogType;
  /** @minLength 1 */
  source: string;
  /** @minLength 1 */
  message: string;
};

export type PostTeamsTeamIdIssuesBody = {
  /** @minLength 1 */
  title: string;
  /** @minLength 1 */
  content: string;
  tag: string[];
  isPublic: boolean;
  logs: PostTeamsTeamIdIssuesBodyLogsItem[];
};

export type PostTeamsTeamIdIssues201 = {
  id: string;
  createdAt: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 이슈에 작성된 일반 댓글과 대댓글 목록을 조회합니다.
 * @summary 댓글 목록 조회
 */
export const getComments = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetComments200>(
    { url: `/issues/${id}/comments`, method: 'GET', signal },
    options,
  );
};

export const getGetCommentsQueryKey = (id: string) => {
  return [`/issues/${id}/comments`] as const;
};

export const getGetCommentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getComments>>,
  TError = ErrorType<GetComments404>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getComments>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCommentsQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getComments>>> = ({
    signal,
  }) => getComments(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getComments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCommentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getComments>>
>;
export type GetCommentsQueryError = ErrorType<GetComments404>;

export function useGetComments<
  TData = Awaited<ReturnType<typeof getComments>>,
  TError = ErrorType<GetComments404>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getComments>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComments>>,
          TError,
          Awaited<ReturnType<typeof getComments>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetComments<
  TData = Awaited<ReturnType<typeof getComments>>,
  TError = ErrorType<GetComments404>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getComments>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComments>>,
          TError,
          Awaited<ReturnType<typeof getComments>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetComments<
  TData = Awaited<ReturnType<typeof getComments>>,
  TError = ErrorType<GetComments404>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getComments>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 댓글 목록 조회
 */

export function useGetComments<
  TData = Awaited<ReturnType<typeof getComments>>,
  TError = ErrorType<GetComments404>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getComments>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCommentsQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 일반 댓글 또는 대댓글을 생성합니다.
 * @summary 댓글 생성
 */
export const postIssuesIdComments = (
  id: string,
  postIssuesIdCommentsBody: BodyType<PostIssuesIdCommentsBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PostIssuesIdComments201>(
    {
      url: `/issues/${id}/comments`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postIssuesIdCommentsBody,
      signal,
    },
    options,
  );
};

export const getPostIssuesIdCommentsMutationOptions = <
  TError = ErrorType<
    PostIssuesIdComments400 | PostIssuesIdComments401 | PostIssuesIdComments404
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postIssuesIdComments>>,
    TError,
    { id: string; data: BodyType<PostIssuesIdCommentsBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postIssuesIdComments>>,
  TError,
  { id: string; data: BodyType<PostIssuesIdCommentsBody> },
  TContext
> => {
  const mutationKey = ['postIssuesIdComments'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postIssuesIdComments>>,
    { id: string; data: BodyType<PostIssuesIdCommentsBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return postIssuesIdComments(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostIssuesIdCommentsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postIssuesIdComments>>
>;
export type PostIssuesIdCommentsMutationBody =
  BodyType<PostIssuesIdCommentsBody>;
export type PostIssuesIdCommentsMutationError = ErrorType<
  PostIssuesIdComments400 | PostIssuesIdComments401 | PostIssuesIdComments404
>;

/**
 * @summary 댓글 생성
 */
export const usePostIssuesIdComments = <
  TError = ErrorType<
    PostIssuesIdComments400 | PostIssuesIdComments401 | PostIssuesIdComments404
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postIssuesIdComments>>,
      TError,
      { id: string; data: BodyType<PostIssuesIdCommentsBody> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postIssuesIdComments>>,
  TError,
  { id: string; data: BodyType<PostIssuesIdCommentsBody> },
  TContext
> => {
  return useMutation(
    getPostIssuesIdCommentsMutationOptions(options),
    queryClient,
  );
};

/**
 * 이슈 작성자가 해결 제안 댓글을 채택합니다.
 * @summary 댓글 채택
 */
export const adoptComment = (
  id: string,
  commentId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AdoptComment200>(
    {
      url: `/issues/${id}/comments/${commentId}/adopt`,
      method: 'POST',
      signal,
    },
    options,
  );
};

export const getAdoptCommentMutationOptions = <
  TError = ErrorType<
    AdoptComment401 | AdoptComment403 | AdoptComment404 | AdoptComment409
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adoptComment>>,
    TError,
    { id: string; commentId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adoptComment>>,
  TError,
  { id: string; commentId: string },
  TContext
> => {
  const mutationKey = ['adoptComment'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adoptComment>>,
    { id: string; commentId: string }
  > = (props) => {
    const { id, commentId } = props ?? {};

    return adoptComment(id, commentId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdoptCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof adoptComment>>
>;

export type AdoptCommentMutationError = ErrorType<
  AdoptComment401 | AdoptComment403 | AdoptComment404 | AdoptComment409
>;

/**
 * @summary 댓글 채택
 */
export const useAdoptComment = <
  TError = ErrorType<
    AdoptComment401 | AdoptComment403 | AdoptComment404 | AdoptComment409
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adoptComment>>,
      TError,
      { id: string; commentId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adoptComment>>,
  TError,
  { id: string; commentId: string },
  TContext
> => {
  return useMutation(getAdoptCommentMutationOptions(options), queryClient);
};

/**
 * 댓글 작성자가 댓글 내용을 수정합니다.
 * @summary 댓글 수정
 */
export const updateComment = (
  id: string,
  commentId: string,
  updateCommentBody: BodyType<UpdateCommentBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<UpdateComment200>(
    {
      url: `/issues/${id}/comments/${commentId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateCommentBody,
      signal,
    },
    options,
  );
};

export const getUpdateCommentMutationOptions = <
  TError = ErrorType<
    UpdateComment400 | UpdateComment401 | UpdateComment403 | UpdateComment404
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateComment>>,
    TError,
    { id: string; commentId: string; data: BodyType<UpdateCommentBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateComment>>,
  TError,
  { id: string; commentId: string; data: BodyType<UpdateCommentBody> },
  TContext
> => {
  const mutationKey = ['updateComment'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateComment>>,
    { id: string; commentId: string; data: BodyType<UpdateCommentBody> }
  > = (props) => {
    const { id, commentId, data } = props ?? {};

    return updateComment(id, commentId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateComment>>
>;
export type UpdateCommentMutationBody = BodyType<UpdateCommentBody>;
export type UpdateCommentMutationError = ErrorType<
  UpdateComment400 | UpdateComment401 | UpdateComment403 | UpdateComment404
>;

/**
 * @summary 댓글 수정
 */
export const useUpdateComment = <
  TError = ErrorType<
    UpdateComment400 | UpdateComment401 | UpdateComment403 | UpdateComment404
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateComment>>,
      TError,
      { id: string; commentId: string; data: BodyType<UpdateCommentBody> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateComment>>,
  TError,
  { id: string; commentId: string; data: BodyType<UpdateCommentBody> },
  TContext
> => {
  return useMutation(getUpdateCommentMutationOptions(options), queryClient);
};

/**
 * Health check API
 */
export const get = (
  params?: GetParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Get200>(
    { url: `/`, method: 'GET', params, signal },
    options,
  );
};

export const getGetQueryKey = (params?: GetParams) => {
  return [`/`, ...(params ? [params] : [])] as const;
};

export const getGetQueryOptions = <
  TData = Awaited<ReturnType<typeof get>>,
  TError = ErrorType<unknown>,
>(
  params?: GetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof get>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof get>>> = ({
    signal,
  }) => get(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof get>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetQueryResult = NonNullable<Awaited<ReturnType<typeof get>>>;
export type GetQueryError = ErrorType<unknown>;

export function useGet<
  TData = Awaited<ReturnType<typeof get>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof get>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof get>>,
          TError,
          Awaited<ReturnType<typeof get>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGet<
  TData = Awaited<ReturnType<typeof get>>,
  TError = ErrorType<unknown>,
>(
  params?: GetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof get>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof get>>,
          TError,
          Awaited<ReturnType<typeof get>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGet<
  TData = Awaited<ReturnType<typeof get>>,
  TError = ErrorType<unknown>,
>(
  params?: GetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof get>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGet<
  TData = Awaited<ReturnType<typeof get>>,
  TError = ErrorType<unknown>,
>(
  params?: GetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof get>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary 회원가입
 */
export const postAuthSignup = (
  postAuthSignupBody?: BodyType<PostAuthSignupBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PostAuthSignup201>(
    {
      url: `/auth/signup`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postAuthSignupBody,
      signal,
    },
    options,
  );
};

export const getPostAuthSignupMutationOptions = <
  TError = ErrorType<PostAuthSignup400 | PostAuthSignup409>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthSignup>>,
    TError,
    { data?: BodyType<PostAuthSignupBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthSignup>>,
  TError,
  { data?: BodyType<PostAuthSignupBody> },
  TContext
> => {
  const mutationKey = ['postAuthSignup'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthSignup>>,
    { data?: BodyType<PostAuthSignupBody> }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthSignup(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthSignupMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthSignup>>
>;
export type PostAuthSignupMutationBody =
  | BodyType<PostAuthSignupBody>
  | undefined;
export type PostAuthSignupMutationError = ErrorType<
  PostAuthSignup400 | PostAuthSignup409
>;

/**
 * @summary 회원가입
 */
export const usePostAuthSignup = <
  TError = ErrorType<PostAuthSignup400 | PostAuthSignup409>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthSignup>>,
      TError,
      { data?: BodyType<PostAuthSignupBody> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthSignup>>,
  TError,
  { data?: BodyType<PostAuthSignupBody> },
  TContext
> => {
  return useMutation(getPostAuthSignupMutationOptions(options), queryClient);
};

/**
 * @summary 로그인
 */
export const postAuthLogin = (
  postAuthLoginBody?: BodyType<PostAuthLoginBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PostAuthLogin200>(
    {
      url: `/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postAuthLoginBody,
      signal,
    },
    options,
  );
};

export const getPostAuthLoginMutationOptions = <
  TError = ErrorType<PostAuthLogin400 | PostAuthLogin401>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthLogin>>,
    TError,
    { data?: BodyType<PostAuthLoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthLogin>>,
  TError,
  { data?: BodyType<PostAuthLoginBody> },
  TContext
> => {
  const mutationKey = ['postAuthLogin'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthLogin>>,
    { data?: BodyType<PostAuthLoginBody> }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthLogin>>
>;
export type PostAuthLoginMutationBody = BodyType<PostAuthLoginBody> | undefined;
export type PostAuthLoginMutationError = ErrorType<
  PostAuthLogin400 | PostAuthLogin401
>;

/**
 * @summary 로그인
 */
export const usePostAuthLogin = <
  TError = ErrorType<PostAuthLogin400 | PostAuthLogin401>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthLogin>>,
      TError,
      { data?: BodyType<PostAuthLoginBody> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthLogin>>,
  TError,
  { data?: BodyType<PostAuthLoginBody> },
  TContext
> => {
  return useMutation(getPostAuthLoginMutationOptions(options), queryClient);
};

/**
 * @summary 로그아웃
 */
export const postAuthLogout = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/auth/logout`, method: 'POST', signal },
    options,
  );
};

export const getPostAuthLogoutMutationOptions = <
  TError = ErrorType<PostAuthLogout401>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthLogout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['postAuthLogout'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthLogout>>,
    void
  > = () => {
    return postAuthLogout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthLogout>>
>;

export type PostAuthLogoutMutationError = ErrorType<PostAuthLogout401>;

/**
 * @summary 로그아웃
 */
export const usePostAuthLogout = <
  TError = ErrorType<PostAuthLogout401>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthLogout>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthLogout>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getPostAuthLogoutMutationOptions(options), queryClient);
};

/**
 * 새로운 팀을 생성합니다.
 * @summary 팀 생성
 */
export const postTeams = (
  postTeamsBody?: BodyType<PostTeamsBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PostTeams201>(
    {
      url: `/teams`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postTeamsBody,
      signal,
    },
    options,
  );
};

export const getPostTeamsMutationOptions = <
  TError = ErrorType<PostTeams400 | PostTeams401>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTeams>>,
    TError,
    { data?: BodyType<PostTeamsBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTeams>>,
  TError,
  { data?: BodyType<PostTeamsBody> },
  TContext
> => {
  const mutationKey = ['postTeams'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTeams>>,
    { data?: BodyType<PostTeamsBody> }
  > = (props) => {
    const { data } = props ?? {};

    return postTeams(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostTeamsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTeams>>
>;
export type PostTeamsMutationBody = BodyType<PostTeamsBody> | undefined;
export type PostTeamsMutationError = ErrorType<PostTeams400 | PostTeams401>;

/**
 * @summary 팀 생성
 */
export const usePostTeams = <
  TError = ErrorType<PostTeams400 | PostTeams401>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postTeams>>,
      TError,
      { data?: BodyType<PostTeamsBody> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postTeams>>,
  TError,
  { data?: BodyType<PostTeamsBody> },
  TContext
> => {
  return useMutation(getPostTeamsMutationOptions(options), queryClient);
};

/**
 * 현재 로그인한 사용자가 속한 팀 목록을 조회합니다.
 * @summary 내가 속한 팀 조회
 */
export const getTeams = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetTeams200>(
    { url: `/teams`, method: 'GET', signal },
    options,
  );
};

export const getGetTeamsQueryKey = () => {
  return [`/teams`] as const;
};

export const getGetTeamsQueryOptions = <
  TData = Awaited<ReturnType<typeof getTeams>>,
  TError = ErrorType<GetTeams401>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getTeams>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTeamsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTeams>>> = ({
    signal,
  }) => getTeams(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTeams>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTeamsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTeams>>
>;
export type GetTeamsQueryError = ErrorType<GetTeams401>;

export function useGetTeams<
  TData = Awaited<ReturnType<typeof getTeams>>,
  TError = ErrorType<GetTeams401>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTeams>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeams>>,
          TError,
          Awaited<ReturnType<typeof getTeams>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTeams<
  TData = Awaited<ReturnType<typeof getTeams>>,
  TError = ErrorType<GetTeams401>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTeams>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeams>>,
          TError,
          Awaited<ReturnType<typeof getTeams>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTeams<
  TData = Awaited<ReturnType<typeof getTeams>>,
  TError = ErrorType<GetTeams401>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTeams>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내가 속한 팀 조회
 */

export function useGetTeams<
  TData = Awaited<ReturnType<typeof getTeams>>,
  TError = ErrorType<GetTeams401>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTeams>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTeamsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 검색 태그를 이용해 이슈를 검색합니다.
 * @summary 이슈 검색
 */
export const getIssuesSearch = (
  params?: GetIssuesSearchParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetIssuesSearch200>(
    { url: `/issues/search`, method: 'GET', params, signal },
    options,
  );
};

export const getGetIssuesSearchQueryKey = (params?: GetIssuesSearchParams) => {
  return [`/issues/search`, ...(params ? [params] : [])] as const;
};

export const getGetIssuesSearchQueryOptions = <
  TData = Awaited<ReturnType<typeof getIssuesSearch>>,
  TError = ErrorType<unknown>,
>(
  params?: GetIssuesSearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIssuesSearch>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetIssuesSearchQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getIssuesSearch>>> = ({
    signal,
  }) => getIssuesSearch(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getIssuesSearch>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetIssuesSearchQueryResult = NonNullable<
  Awaited<ReturnType<typeof getIssuesSearch>>
>;
export type GetIssuesSearchQueryError = ErrorType<unknown>;

export function useGetIssuesSearch<
  TData = Awaited<ReturnType<typeof getIssuesSearch>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetIssuesSearchParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIssuesSearch>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIssuesSearch>>,
          TError,
          Awaited<ReturnType<typeof getIssuesSearch>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetIssuesSearch<
  TData = Awaited<ReturnType<typeof getIssuesSearch>>,
  TError = ErrorType<unknown>,
>(
  params?: GetIssuesSearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIssuesSearch>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIssuesSearch>>,
          TError,
          Awaited<ReturnType<typeof getIssuesSearch>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetIssuesSearch<
  TData = Awaited<ReturnType<typeof getIssuesSearch>>,
  TError = ErrorType<unknown>,
>(
  params?: GetIssuesSearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIssuesSearch>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 이슈 검색
 */

export function useGetIssuesSearch<
  TData = Awaited<ReturnType<typeof getIssuesSearch>>,
  TError = ErrorType<unknown>,
>(
  params?: GetIssuesSearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIssuesSearch>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetIssuesSearchQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary 최신 이슈 피드 조회
 */
export const getIssuesPublic = (
  params?: GetIssuesPublicParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetPublicIssuesResponse>(
    { url: `/issues/public`, method: 'GET', params, signal },
    options,
  );
};

export const getGetIssuesPublicQueryKey = (params?: GetIssuesPublicParams) => {
  return [`/issues/public`, ...(params ? [params] : [])] as const;
};

export const getGetIssuesPublicQueryOptions = <
  TData = Awaited<ReturnType<typeof getIssuesPublic>>,
  TError = ErrorType<PublicBadRequest>,
>(
  params?: GetIssuesPublicParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIssuesPublic>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetIssuesPublicQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getIssuesPublic>>> = ({
    signal,
  }) => getIssuesPublic(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getIssuesPublic>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetIssuesPublicQueryResult = NonNullable<
  Awaited<ReturnType<typeof getIssuesPublic>>
>;
export type GetIssuesPublicQueryError = ErrorType<PublicBadRequest>;

export function useGetIssuesPublic<
  TData = Awaited<ReturnType<typeof getIssuesPublic>>,
  TError = ErrorType<PublicBadRequest>,
>(
  params: undefined | GetIssuesPublicParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIssuesPublic>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIssuesPublic>>,
          TError,
          Awaited<ReturnType<typeof getIssuesPublic>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetIssuesPublic<
  TData = Awaited<ReturnType<typeof getIssuesPublic>>,
  TError = ErrorType<PublicBadRequest>,
>(
  params?: GetIssuesPublicParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIssuesPublic>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIssuesPublic>>,
          TError,
          Awaited<ReturnType<typeof getIssuesPublic>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetIssuesPublic<
  TData = Awaited<ReturnType<typeof getIssuesPublic>>,
  TError = ErrorType<PublicBadRequest>,
>(
  params?: GetIssuesPublicParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIssuesPublic>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 최신 이슈 피드 조회
 */

export function useGetIssuesPublic<
  TData = Awaited<ReturnType<typeof getIssuesPublic>>,
  TError = ErrorType<PublicBadRequest>,
>(
  params?: GetIssuesPublicParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIssuesPublic>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetIssuesPublicQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 팀에 속한 특정 이슈의 상세 정보를 조회합니다.
 * @summary 이슈 상세 조회
 */
export const getTeamsTeamIdIssuesIssueId = (
  teamId: string,
  issueId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetTeamsTeamIdIssuesIssueId200>(
    { url: `/teams/${teamId}/issues/${issueId}`, method: 'GET', signal },
    options,
  );
};

export const getGetTeamsTeamIdIssuesIssueIdQueryKey = (
  teamId: string,
  issueId: string,
) => {
  return [`/teams/${teamId}/issues/${issueId}`] as const;
};

export const getGetTeamsTeamIdIssuesIssueIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getTeamsTeamIdIssuesIssueId>>,
  TError = ErrorType<DetailBadRequest | NotFound>,
>(
  teamId: string,
  issueId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTeamsTeamIdIssuesIssueId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetTeamsTeamIdIssuesIssueIdQueryKey(teamId, issueId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTeamsTeamIdIssuesIssueId>>
  > = ({ signal }) =>
    getTeamsTeamIdIssuesIssueId(teamId, issueId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(teamId && issueId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTeamsTeamIdIssuesIssueId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTeamsTeamIdIssuesIssueIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTeamsTeamIdIssuesIssueId>>
>;
export type GetTeamsTeamIdIssuesIssueIdQueryError = ErrorType<
  DetailBadRequest | NotFound
>;

export function useGetTeamsTeamIdIssuesIssueId<
  TData = Awaited<ReturnType<typeof getTeamsTeamIdIssuesIssueId>>,
  TError = ErrorType<DetailBadRequest | NotFound>,
>(
  teamId: string,
  issueId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTeamsTeamIdIssuesIssueId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeamsTeamIdIssuesIssueId>>,
          TError,
          Awaited<ReturnType<typeof getTeamsTeamIdIssuesIssueId>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTeamsTeamIdIssuesIssueId<
  TData = Awaited<ReturnType<typeof getTeamsTeamIdIssuesIssueId>>,
  TError = ErrorType<DetailBadRequest | NotFound>,
>(
  teamId: string,
  issueId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTeamsTeamIdIssuesIssueId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeamsTeamIdIssuesIssueId>>,
          TError,
          Awaited<ReturnType<typeof getTeamsTeamIdIssuesIssueId>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTeamsTeamIdIssuesIssueId<
  TData = Awaited<ReturnType<typeof getTeamsTeamIdIssuesIssueId>>,
  TError = ErrorType<DetailBadRequest | NotFound>,
>(
  teamId: string,
  issueId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTeamsTeamIdIssuesIssueId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 이슈 상세 조회
 */

export function useGetTeamsTeamIdIssuesIssueId<
  TData = Awaited<ReturnType<typeof getTeamsTeamIdIssuesIssueId>>,
  TError = ErrorType<DetailBadRequest | NotFound>,
>(
  teamId: string,
  issueId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTeamsTeamIdIssuesIssueId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTeamsTeamIdIssuesIssueIdQueryOptions(
    teamId,
    issueId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 팀에 새로운 이슈를 등록합니다.
 * @summary 이슈 등록
 */
export const postTeamsTeamIdIssues = (
  teamId: string,
  postTeamsTeamIdIssuesBody?: BodyType<PostTeamsTeamIdIssuesBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PostTeamsTeamIdIssues201>(
    {
      url: `/teams/${teamId}/issues`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postTeamsTeamIdIssuesBody,
      signal,
    },
    options,
  );
};

export const getPostTeamsTeamIdIssuesMutationOptions = <
  TError = ErrorType<CreateBadRequest | Unauthorized | Forbidden>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTeamsTeamIdIssues>>,
    TError,
    { teamId: string; data?: BodyType<PostTeamsTeamIdIssuesBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTeamsTeamIdIssues>>,
  TError,
  { teamId: string; data?: BodyType<PostTeamsTeamIdIssuesBody> },
  TContext
> => {
  const mutationKey = ['postTeamsTeamIdIssues'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTeamsTeamIdIssues>>,
    { teamId: string; data?: BodyType<PostTeamsTeamIdIssuesBody> }
  > = (props) => {
    const { teamId, data } = props ?? {};

    return postTeamsTeamIdIssues(teamId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostTeamsTeamIdIssuesMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTeamsTeamIdIssues>>
>;
export type PostTeamsTeamIdIssuesMutationBody =
  | BodyType<PostTeamsTeamIdIssuesBody>
  | undefined;
export type PostTeamsTeamIdIssuesMutationError = ErrorType<
  CreateBadRequest | Unauthorized | Forbidden
>;

/**
 * @summary 이슈 등록
 */
export const usePostTeamsTeamIdIssues = <
  TError = ErrorType<CreateBadRequest | Unauthorized | Forbidden>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postTeamsTeamIdIssues>>,
      TError,
      { teamId: string; data?: BodyType<PostTeamsTeamIdIssuesBody> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postTeamsTeamIdIssues>>,
  TError,
  { teamId: string; data?: BodyType<PostTeamsTeamIdIssuesBody> },
  TContext
> => {
  return useMutation(
    getPostTeamsTeamIdIssuesMutationOptions(options),
    queryClient,
  );
};
